#!/usr/bin/env bash
path_to_file=""
file_name=".envrc"
folder_to_look_in="$PWD"
while :
do
    # check if file exists
    if [ -f "$folder_to_look_in/$file_name" ]
    then
        path_to_file="$folder_to_look_in/$file_name"
        break
    else
        if [ "$folder_to_look_in" = "/" ]
        then
            break
        else
            folder_to_look_in="$(dirname "$folder_to_look_in")"
        fi
    fi
done
if [ -z "$path_to_file" ]
then
    #
    # what to do if file never found
    #
    echo "I couldn't find your .envrc file"
    echo "please run the command from the folder with the .envrc"
else

    # go to the path
    cd "$(dirname "$path_to_file")"
    # source it
    . ./.envrc

    # 
    # run moveit demo
    # 
    roslaunch sb_moveit_config demo.launch
fi